services:
  nseindia:
    image: imcodeman/nseindia
    platform: linux/amd64
    ports:
      - "3001:3001"

  mcp:
    build:
      context: .
      dockerfile: docker/mcp.dockerfile
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_USER_AGENT=${REDDIT_USER_AGENT}
      - HOST=0.0.0.0
    ports:
      - "8000:8000"
    depends_on:
      - nseindia

  adk:
    build:
      context: .
      dockerfile: docker/adk.dockerfile
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_USER_AGENT=${REDDIT_USER_AGENT}
      - LITE_LLM_MODEL=${LITE_LLM_MODEL}
      - LITE_LLM_API_KEY=${LITE_LLM_API_KEY}
      - HOST=0.0.0.0
      - MCP_URL=http://mcp:8000/sse
    ports:
      - "8080:8080"
    depends_on:
      - mcp